# -*- coding: utf-8 -*-
"""oil_spill_detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OZ48ym0L_HMlpk1ECduJorQOM8xZYedv
"""

# Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

# Define the base path for the project directory in Google Drive
base_path = '/content/drive/mydrive/oil_spill_detection'

"""Cell 2: Install Required Libraries"""

# The pip install command for segmentation-models-pytorch and albumentations has been moved to the main import cell (_5UTjhPu8x8P) to ensure dependencies are met before import. This cell is now empty as its content has been relocated.

"""Cell 3: Import Libraries and Set Paths

"""

!pip install segmentation-models-pytorch albumentations -q

import os
import numpy as np
from PIL import Image
import torch
from torch.utils.data import Dataset, DataLoader
import matplotlib.pyplot as plt
import albumentations as A
from albumentations.pytorch import ToTensorV2
import segmentation_models_pytorch as smp
from tqdm import tqdm
import cv2

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
IMGSIZE = (256, 256)
BATCH_SIZE = 8

"""Cell 4: Define Albumentations Augmentations python"""

train_aug = A.Compose([
    A.Resize(IMGSIZE[0], IMGSIZE[1]),
    A.HorizontalFlip(p=0.5),
    A.VerticalFlip(p=0.5),
    A.RandomRotate90(p=0.5),
    A.ShiftScaleRotate(shift_limit=0.12, scale_limit=0.15, rotate_limit=20, p=0.7),
    A.RandomBrightnessContrast(p=0.4),
    A.OneOf([
        A.GaussianBlur(p=1.0),
        A.MotionBlur(p=1.0),
        A.MedianBlur(blur_limit=3, p=1.0)
    ], p=0.3),
    A.Normalize(mean=(0.485, 0.456, 0.406), std=(0.229, 0.224, 0.225)),
    ToTensorV2()
])
val_aug = A.Compose([
    A.Resize(IMGSIZE[0], IMGSIZE[1]),
    A.Normalize(mean=(0.485, 0.456, 0.406), std=(0.229, 0.224, 0.225)),
    ToTensorV2()
])

"""Cell 5: Dataset Preparation and Loader"""

import os
from torch.utils.data import Dataset, DataLoader
import numpy as np
from PIL import Image
# cv2 is now imported in cell _5UTjhPu8x8P

# Base path matching your Google Drive folder name exactly
base_path = '/content/drive/MyDrive/oil_spill_dataset'

# ✅ Correct folder names
TRAIN_IMG = os.path.join(base_path, 'train/images')
TRAIN_MASK = os.path.join(base_path, 'train/masks')
VAL_IMG = os.path.join(base_path, 'val/images')
VAL_MASK = os.path.join(base_path, 'val/masks')

class OilSpillDataset(Dataset):
    def __init__(self, img_dir, mask_dir, transforms=None):
        self.imgs = sorted([os.path.join(img_dir, fname) for fname in os.listdir(img_dir)])
        self.masks = sorted([os.path.join(mask_dir, fname) for fname in os.listdir(mask_dir)])
        self.transforms = transforms

        if len(self.imgs) != len(self.masks):
            raise ValueError(f"Number of images ({len(self.imgs)}) and masks ({len(self.masks)}) do not match in {img_dir} and {mask_dir}")

    def __len__(self):
        return len(self.imgs)

    def __getitem__(self, idx):
        img = cv2.imread(self.imgs[idx])
        img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

        mask = cv2.imread(self.masks[idx], cv2.IMREAD_GRAYSCALE)
        mask = np.expand_dims(mask, axis=-1)
        mask = (mask > 127).astype(np.float32)

        if self.transforms:
            augmented = self.transforms(image=img, mask=mask)
            img = augmented['image']
            mask = augmented['mask']

        if mask.ndim == 2:
            mask = mask.unsqueeze(0)
        elif mask.ndim == 3 and mask.shape[-1] == 1:
            mask = mask.permute(2, 0, 1)

        return img, mask

# Ensure train_aug and val_aug are defined earlier
# BATCH_SIZE is already defined globally in cell _5UTjhPu8x8P
trainset = OilSpillDataset(TRAIN_IMG, TRAIN_MASK, train_aug)
valset = OilSpillDataset(VAL_IMG, VAL_MASK, val_aug)

# Removed pin_memory=True if CUDA is not available to prevent warnings and unnecessary overhead
train_loader = DataLoader(trainset, batch_size=BATCH_SIZE, shuffle=True, num_workers=2, pin_memory=False if not torch.cuda.is_available() else True)
val_loader = DataLoader(valset, batch_size=BATCH_SIZE, shuffle=False, num_workers=2, pin_memory=False if not torch.cuda.is_available() else True)

"""Cell 6: Visualize a Batch with Color Mapping



"""

def color_mask(mask):
    # mask: HxW, 1 or 0
    h, w = mask.shape
    cmask = np.zeros((h, w, 3), dtype=np.uint8)
    cmask[mask==1] = [255, 0, 0] # Oil spill: red
    return cmask

# Get a batch from the validation loader
imgs, masks = next(iter(val_loader))
img = imgs[0].permute(1,2,0).cpu().numpy()
mask = masks[0][0].cpu().numpy()

# De-normalize the image for display
img_display = (img * [0.229,0.224,0.225] + [0.485,0.456,0.406]).clip(0,1)

# Create color masks for visualization
ground_truth_cmask = color_mask(mask)

# Plotting
plt.figure(figsize=(12, 6)) # Adjusted figure size

plt.subplot(1, 2, 1)
plt.imshow(img_display)
plt.title("Original Image")
plt.axis("off")

plt.subplot(1, 2, 2)
plt.imshow(ground_truth_cmask)
plt.title("Ground Truth Mask")
plt.axis("off")

plt.tight_layout()
plt.show()

# Note: To see the predicted mask, you need to run the cell where the model is defined first (Cell 7 or similar)
# and then add code to this cell or a new cell to get predictions from the model.

"""Cell 7: Define Model — UNet (Pretrained, Robust)"""

import os
os.environ['HF_HUB_DISABLE_TELEMETRY'] = '1'
import segmentation_models_pytorch as smp

# You can experiment with different architectures available in smpCell 7: Define Model — UNet (Pretrained, Robust)
# Some common options include:
# smp.Unet
# smp.UnetPlusPlus
# smp.DeepLabV3
# smp.DeepLabV3Plus
# smp.FPN
# smp.PAN

# Choose your desired model architecture here
model_architecture = "Unet" # You can change this to try other models

if model_architecture == "Unet":
    model = smp.Unet(
        encoder_name="resnet50",  # You can also experiment with different encoders
        encoder_weights="imagenet", # Use "imagenet" for pretrained weights, or None
        in_channels=3,
        classes=1,
        activation=None # Use None for sigmoid activation with BCEWithLogitsLoss
    ).to(DEVICE)
elif model_architecture == "UnetPlusPlus":
     model = smp.UnetPlusPlus(
        encoder_name="resnet50",
        encoder_weights="imagenet",
        in_channels=3,
        classes=1,
        activation=None
    ).to(DEVICE)
# Add more elif blocks for other architectures you want to experiment with

print(f"Using model architecture: {model_architecture}")

"""Cell 8: Loss, Optimizer, Mixed Precision Setup"""

import torch.nn as nn
from torch.cuda.amp import GradScaler, autocast
import torch.optim as optim # Import optim

bce_loss = nn.BCEWithLogitsLoss()
dice_loss = smp.losses.DiceLoss(mode='binary')
def total_loss(pred, target):
    return 0.5*dice_loss(pred, target) + 0.5*bce_loss(pred, target)

# Experiment with different learning rates and optimizers here
learning_rate = 1e-6 # Changed learning rate to 1e-6
optimizer = optim.AdamW(model.parameters(), lr=learning_rate, weight_decay=1e-4) # Switched back to AdamW


# You can also try other optimizers like SGD:
# optimizer = optim.SGD(model.parameters(), lr=learning_rate, momentum=0.9, weight_decay=1e-4)


scaler = torch.amp.GradScaler('cuda', enabled=torch.cuda.is_available())

"""Cell 9: IoU and Dice Metrics"""

def iou_score(preds, targets, threshold=0.5, eps=1e-6):
    preds = torch.sigmoid(preds)
    preds = (preds > threshold).float()
    preds = preds.view(preds.size(0), -1)
    targets = targets.view(targets.size(0), -1)
    intersection = (preds * targets).sum(1)
    union = preds.sum(1) + targets.sum(1) - intersection
    iou = (intersection + eps) / (union + eps)
    return iou.mean().item()

def dice_coeff(preds, targets, threshold=0.5, eps=1e-6):
    preds = torch.sigmoid(preds)
    preds = (preds > threshold).float()
    preds = preds.view(preds.size(0), -1)
    targets = targets.view(targets.size(0), -1)
    intersection = (preds * targets).sum(1)
    dice = (2. * intersection + eps) / (preds.sum(1) + targets.sum(1) + eps)
    return dice.mean().item()

"""Cell 10: Training & Validation Loops with AMP"""

import torch
import torch.nn.functional as F
from torch.optim.lr_scheduler import CosineAnnealingLR
from tqdm import tqdm

# ⚙️ Config
EPOCHS = 30
LR = 3e-4
GRAD_ACCUM_STEPS = 2
# DEVICE is already defined globally in cell _5UTjhPu8x8P, so no need to redefine.

# ✅ Optimizer and Scheduler: These are specific to this training run.
optimizer = torch.optim.AdamW(model.parameters(), lr=LR, weight_decay=1e-4)
scheduler = CosineAnnealingLR(optimizer, T_max=EPOCHS, eta_min=1e-6)
# scaler is already defined globally in cell F64THg2jD8sP, so no need to redefine.

# ✅ Loss: bce_loss, dice_loss, and total_loss are defined globally in cell F64THg2jD8sP.
# We will use the globally defined loss functions.

# ✅ Metrics
def metrics(preds, targets, threshold=0.5):
    probs = torch.sigmoid(preds)
    preds = (probs > threshold).float()
    targets = targets.float()
    inter = (preds * targets).sum()
    union = preds.sum() + targets.sum() - inter
    dice = (2. * inter) / (preds.sum() + targets.sum() + 1e-7)
    iou = (inter + 1e-7) / (union + 1e-7)
    acc = (preds == targets).float().mean()
    return dice.item(), iou.item(), acc.item()

# History tracking lists
train_losses, val_losses = [], []
train_dices, val_dices = [], []
train_ious, val_ious = [], []
train_accs, val_accs = [], []

# ✅ Training
best_score = 0.0
for epoch in range(EPOCHS):
    model.train()
    # Initialize epoch-level accumulators
    current_train_loss = 0.0
    current_train_dice = 0.0
    current_train_iou = 0.0
    current_train_acc = 0.0
    num_train_samples = 0

    optimizer.zero_grad() # Zero gradients once at the start of the epoch for accumulation

    for i, (imgs, masks) in enumerate(tqdm(train_loader, desc=f"Epoch {epoch+1}/{EPOCHS} Training")):
        imgs, masks = imgs.to(DEVICE), masks.to(DEVICE)
        num_train_samples += imgs.size(0)

        with torch.cuda.amp.autocast(): # Use autocast directly from torch.cuda.amp
            logits = model(imgs)
            loss = total_loss(logits, masks)
        # Scale loss before backward for accumulation
        scaler.scale(loss / GRAD_ACCUM_STEPS).backward()

        if (i + 1) % GRAD_ACCUM_STEPS == 0:
            scaler.step(optimizer)
            scaler.update()
            optimizer.zero_grad() # Zero gradients after update

        d, iou, acc = metrics(logits, masks)
        current_train_loss += loss.item() * imgs.size(0)
        current_train_dice += d * imgs.size(0)
        current_train_iou += iou * imgs.size(0)
        current_train_acc += acc * imgs.size(0)

    # Perform a final optimization step if there are remaining gradients
    if (i + 1) % GRAD_ACCUM_STEPS != 0:
        scaler.step(optimizer)
        scaler.update()
        optimizer.zero_grad()

    # 🔍 Validation
    model.eval()
    current_val_loss = 0.0
    current_val_dice = 0.0
    current_val_iou = 0.0
    current_val_acc = 0.0
    num_val_samples = 0

    with torch.no_grad():
        for imgs, masks in tqdm(val_loader, desc=f"Epoch {epoch+1}/{EPOCHS} Validation"):
            imgs, masks = imgs.to(DEVICE), masks.to(DEVICE)
            num_val_samples += imgs.size(0)
            with torch.cuda.amp.autocast():
                logits = model(imgs)
                loss = total_loss(logits, masks)
            d, iou, acc = metrics(logits, masks)
            current_val_loss += loss.item() * imgs.size(0)
            current_val_dice += d * imgs.size(0)
            current_val_iou += iou * imgs.size(0)
            current_val_acc += acc * imgs.size(0)

    # ⚡ Epoch summary
    train_loss_epoch = current_train_loss / num_train_samples
    val_loss_epoch = current_val_loss / num_val_samples
    train_dice_epoch = current_train_dice / num_train_samples
    val_dice_epoch = current_val_dice / num_val_samples
    train_iou_epoch = current_train_iou / num_train_samples
    val_iou_epoch = current_val_iou / num_val_samples
    val_acc_epoch = current_val_acc / num_val_samples

    # Store history
    train_losses.append(train_loss_epoch)
    val_losses.append(val_loss_epoch)
    train_dices.append(train_dice_epoch)
    val_dices.append(val_dice_epoch)
    train_ious.append(train_iou_epoch)
    val_ious.append(val_iou_epoch)
    train_accs.append(current_train_acc / num_train_samples) # Also store train_acc
    val_accs.append(val_acc_epoch)

    print(f"Epoch [{epoch+1}/{EPOCHS}] | Train Loss: {train_loss_epoch:.4f} | Val Loss: {val_loss_epoch:.4f} | Train Dice: {train_dice_epoch:.4f} | Val Dice: {val_dice_epoch:.4f} | Val IoU: {val_iou_epoch:.4f} | Val Acc: {val_acc_epoch:.4f}")

    scheduler.step()

    # 🏆 Save best model
    score = 0.7 * val_dice_epoch + 0.3 * val_iou_epoch
    if score > best_score:
        best_score = score
        torch.save(model.state_dict(), "best_model_optimized.pth")
        print(f"✅ New best model saved with combined score {best_score:.4f}")

import torch

# Define the path where you want to save the model
save_path = "my_model.pth"

# Save the model's state dictionary
torch.save(model.state_dict(), save_path)

print(f"Model saved to {save_path}")

import torch

# Load the best model's weights
# Make sure your model architecture is defined before loading weights
# For example, if you used Unet with resnet50 encoder:
# model = smp.Unet(
#     encoder_name="resnet50",
#     encoder_weights=None, # Set to None for inference or if you don't want to load imagenet weights again
#     in_channels=3,
#     classes=1,
#     activation=None
# ).to(DEVICE)

# Path to your saved model
load_path = "best_model_optimized.pth" # Or "my_model.pth" if you used the manual save code

model.load_state_dict(torch.load(load_path, map_location=DEVICE))
model.eval() # Set the model to evaluation mode after loading

print(f"Model loaded from {load_path} and set to evaluation mode.")

!pip install segmentation-models-pytorch -q

!streamlit run app.py

# Assuming you have lists to store the history like this in your training loop:
# train_losses = []
# val_losses = []
# train_ious = []
# val_ious = []
# train_dices = []
# val_dices = []

# Example plotting code (replace with your actual history lists)

plt.figure(figsize=(12, 8))

# Plot Loss
plt.subplot(2, 2, 1)
plt.plot(train_losses, label='Train Loss')
plt.plot(val_losses, label='Val Loss')
plt.title('Loss over Epochs')
plt.xlabel('Epoch')
plt.ylabel('Loss')
plt.legend()
plt.grid(True)

# Plot IoU
plt.subplot(2, 2, 2)
plt.plot(train_ious, label='Train IoU')
plt.plot(val_ious, label='Val IoU')
plt.title('IoU over Epochs')
plt.xlabel('Epoch')
plt.ylabel('IoU')
plt.legend()
plt.grid(True)

# Plot Dice
plt.subplot(2, 2, 3)
plt.plot(train_dices, label='Train Dice')
plt.plot(val_dices, label='Val Dice')
plt.title('Dice over Epochs')
plt.xlabel('Epoch')
plt.ylabel('Dice')
plt.legend()
plt.grid(True)

plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
import numpy as np
import torch

# Assuming the model and DEVICE are already defined
# Load the best model (if not already loaded)
# model.load_state_dict(torch.load("best_model.pth", map_location=DEVICE))
# model.eval() # Set model to evaluation mode

# Assuming val_loader is defined and accessible
# Get a batch from the validation loader
imgs, masks = next(iter(val_loader))

# Select the first image from the batch
img = imgs[0]

# Move image to device and add batch dimension for prediction
img_tensor = img.unsqueeze(0).to(DEVICE)

# Get raw logits from the model
with torch.no_grad():
    logits = model(img_tensor)
    # Apply sigmoid to get probabilities
    probability_map = torch.sigmoid(logits).squeeze().cpu().numpy()

# De-normalize the image for display if it was normalized during preprocessing
# Assuming normalization mean=(0.485, 0.456, 0.406), std=(0.229, 0.224, 0.225)
img_display = img.permute(1, 2, 0).cpu().numpy()
mean = np.array([0.485, 0.456, 0.406])
std = np.array([0.229, 0.224, 0.225])
img_display = std * img_display + mean
img_display = np.clip(img_display, 0, 1)


# Plotting the original image and the confidence heatmap
plt.figure(figsize=(12, 6))

plt.subplot(1, 2, 1)
plt.imshow(img_display)
plt.title("Original Image")
plt.axis("off")

plt.subplot(1, 2, 2)
plt.imshow(probability_map, cmap='viridis') # Using 'viridis' colormap for heatmap
plt.title("Confidence Heatmap")
plt.colorbar(label="Probability")
plt.axis("off")

plt.tight_layout()
plt.show()

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import numpy as np
# from PIL import Image
# import torch
# import matplotlib.pyplot as plt
# import segmentation_models_pytorch as smp
# import cv2
# import os
# import sqlite3
# import pandas as pd
# from datetime import datetime
# 
# # Define DEVICE and model architecture (must match training)
# DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
# IMGSIZE = (256, 256) # Must match the size used during training
# 
# # Define the base path for saving predictions (within Google Drive)
# # This assumes '/content/drive/MyDrive' is mounted
# base_gdrive_path = '/content/drive/MyDrive/oil_spill_dataset' # Ensure this matches your mounted Drive path
# PREDICTION_SAVE_DIR = os.path.join(base_gdrive_path, 'predictions')
# os.makedirs(PREDICTION_SAVE_DIR, exist_ok=True)
# 
# # Define the path to the saved model (ensure this path is correct)
# model_path = "best_model_optimized.pth" # Using the optimized model
# 
# # Database setup
# DATABASE_NAME = os.path.join(PREDICTION_SAVE_DIR, 'predictions.db') # Store DB in Drive
# 
# def init_db():
#     conn = sqlite3.connect(DATABASE_NAME)
#     cursor = conn.cursor()
#     cursor.execute('''
#         CREATE TABLE IF NOT EXISTS predictions (
#             id INTEGER PRIMARY KEY AUTOINCREMENT,
#             timestamp TEXT,
#             original_image_path TEXT,
#             prediction_mask_path TEXT,
#             oil_spill_percentage REAL
#         )
#     ''')
#     conn.commit()
#     conn.close()
# 
# def insert_prediction(timestamp, original_image_path, prediction_mask_path, oil_spill_percentage):
#     conn = sqlite3.connect(DATABASE_NAME)
#     cursor = conn.cursor()
#     cursor.execute('''
#         INSERT INTO predictions (timestamp, original_image_path, prediction_mask_path, oil_spill_percentage)
#         VALUES (?, ?, ?, ?)
#     ''', (timestamp, original_image_path, prediction_mask_path, oil_spill_percentage))
#     conn.commit()
#     conn.close()
# 
# def get_all_predictions():
#     conn = sqlite3.connect(DATABASE_NAME)
#     df = pd.read_sql_query("SELECT * FROM predictions ORDER BY timestamp DESC", conn)
#     conn.close()
#     return df
# 
# # Initialize database on app startup
# init_db()
# 
# # Load the trained model
# model = None
# if not os.path.exists(model_path):
#     st.error(f"Model file not found at: {model_path}. Please ensure 'best_model_optimized.pth' is in the correct location.")
# else:
#     try:
#         model = smp.Unet(
#             encoder_name="resnet50",
#             encoder_weights=None, # No imagenet weights needed for inference
#             in_channels=3,
#             classes=1,
#             activation=None
#         ).to(DEVICE)
#         model.load_state_dict(torch.load(model_path, map_location=DEVICE))
#         model.eval() # Set model to evaluation mode
#     except Exception as e:
#         st.error(f"Error loading model state dictionary: {e}")
#         model = None # Set model to None if loading fails
# 
# # Function to predict mask
# @st.cache_data # Cache the prediction function
# def predict_mask(image, _model, device, img_size):
#     if _model is None:
#         return None # Return None if model failed to load
# 
#     # Preprocess the image
#     image_cv2 = cv2.cvtColor(np.array(image), cv2.COLOR_RGB2BGR) # Convert PIL to OpenCV BGR
#     image_resized = cv2.resize(image_cv2, img_size) # Resize
#     image_normalized = image_resized / 255.0 # Normalize to [0, 1]
# 
#     # Apply the same normalization as training
#     mean = np.array([0.485, 0.456, 0.406])
#     std = np.array([0.229, 0.224, 0.225])
#     image_processed = (image_normalized - mean) / std
# 
#     image_tensor = np.transpose(image_processed, (2, 0, 1)) # Change to CxHxW
#     image_tensor = torch.from_numpy(image_tensor).float().unsqueeze(0).to(device) # To tensor and add batch dim
# 
#     with torch.no_grad():
#         logits = _model(image_tensor)
#         pred_mask_proba = torch.sigmoid(logits).squeeze().cpu().numpy() # Apply sigmoid and remove batch/channel dims
# 
#     # Apply a threshold (can be adjusted)
#     threshold = 0.5
#     binary_mask = (pred_mask_proba > threshold).astype(np.uint8)
# 
#     return binary_mask
# 
# # Function to color the mask
# def color_mask(mask):
#     # mask: HxW, 1 or 0
#     h, w = mask.shape
#     cmask = np.zeros((h, w, 3), dtype=np.uint8)
#     # Color oil spill area red
#     cmask[mask==1] = [255, 0, 0]
#     return cmask
# 
# # Streamlit app
# st.set_page_config(layout="wide") # Use wide layout for better display
# st.title("🌊 Oil Spill Detection & Monitoring 🚢")
# 
# # Sidebar for navigation
# st.sidebar.title("Navigation")
# page = st.sidebar.radio("Go to", ["Detect Spill", "Prediction History"])
# 
# if page == "Detect Spill":
#     st.header("Upload an image to detect oil spills")
# 
#     uploaded_file = st.file_uploader("Choose an image...", type=["jpg", "jpeg", "png"])
# 
#     if uploaded_file is not None:
#         image = Image.open(uploaded_file).convert("RGB")
#         st.image(image, caption="Uploaded Image.", width=700)
# 
#         if st.button("Predict Oil Spill"):
#             if model is not None:
#                 with st.spinner('Detecting oil spill...'):
#                     pred_mask_binary = predict_mask(image, model, DEVICE, IMGSIZE)
# 
#                 if pred_mask_binary is not None:
#                     # Calculate predicted oil spill area (number of oil spill pixels)
#                     oil_spill_pixels = np.sum(pred_mask_binary)
#                     total_pixels = pred_mask_binary.size
#                     oil_spill_percentage = (oil_spill_pixels / total_pixels) * 100 if total_pixels > 0 else 0
# 
#                     # Convert the predicted mask to a color mask for visualization
#                     colored_pred_mask = color_mask(pred_mask_binary)
# 
#                     col1, col2 = st.columns(2)
#                     with col1:
#                         st.subheader("Original Image")
#                         st.image(image, width=700)
#                     with col2:
#                         st.subheader("Predicted Oil Spill Mask")
#                         st.image(colored_pred_mask, caption=f"Oil Spill: {oil_spill_percentage:.2f}%", width=700)
# 
#                     st.subheader("Prediction Summary")
#                     st.info(f"Predicted oil spill area: Approximately {oil_spill_pixels} pixels ({oil_spill_percentage:.2f}% of the image).")
# 
#                     # Save prediction details to database and file system
#                     current_time = datetime.now().strftime("%Y%m%d_%H%M%S")
#                     original_filename = f"original_{current_time}_{uploaded_file.name}"
#                     mask_filename = f"mask_{current_time}_{uploaded_file.name}"
# 
#                     original_image_save_path = os.path.join(PREDICTION_SAVE_DIR, original_filename)
#                     mask_image_save_path = os.path.join(PREDICTION_SAVE_DIR, mask_filename)
# 
#                     # Save original image
#                     image.save(original_image_save_path)
# 
#                     # Save predicted mask (as an image)
#                     # Convert to PIL Image first for saving
#                     mask_img_to_save = Image.fromarray(colored_pred_mask)
#                     mask_img_to_save.save(mask_image_save_path)
# 
#                     insert_prediction(
#                         datetime.now().isoformat(),
#                         original_image_save_path,
#                         mask_image_save_path,
#                         oil_spill_percentage
#                     )
#                     st.success("Prediction saved to history!")
# 
#                     if oil_spill_percentage > 10: # Example threshold for significant spill
#                         st.warning("This indicates a significant potential oil spill. Immediate action and further investigation are recommended.")
#                     elif oil_spill_percentage > 1: # Example threshold for minor spill
#                         st.info("This suggests a possible minor oil spill. Monitoring and further assessment are advised.")
#                     else:
#                         st.success("This indicates a low probability of a significant oil spill in this area. Continued vigilance is always a good practice.")
# 
#                 else:
#                     st.error("Prediction failed due to model loading issues.")
#             else:
#                 st.error("Model not loaded. Please check the model file path and try again.")
# elif page == "Prediction History":
#     st.header("Historical Oil Spill Predictions")
# 
#     predictions_df = get_all_predictions()
# 
#     if not predictions_df.empty:
#         st.dataframe(predictions_df, use_container_width=True)
# 
#         st.subheader("View Specific Prediction")
#         selected_id = st.selectbox("Select Prediction ID to view:", predictions_df['id'].tolist())
# 
#         if selected_id:
#             selected_prediction = predictions_df[predictions_df['id'] == selected_id].iloc[0]
# 
#             col1_hist, col2_hist = st.columns(2)
#             with col1_hist:
#                 st.subheader("Original Image")
#                 original_img_path = selected_prediction['original_image_path']
#                 if os.path.exists(original_img_path):
#                     st.image(Image.open(original_img_path), width=700)
#                 else:
#                     st.warning(f"Original image not found at: {original_img_path}")
#             with col2_hist:
#                 st.subheader("Predicted Mask")
#                 mask_img_path = selected_prediction['prediction_mask_path']
#                 if os.path.exists(mask_img_path):
#                     st.image(Image.open(mask_img_path), width=700)
#                 else:
#                     st.warning(f"Prediction mask not found at: {mask_img_path}")
# 
#             st.write(f"**Timestamp:** {selected_prediction['timestamp']}")
#             st.write(f"**Oil Spill Percentage:** {selected_prediction['oil_spill_percentage']:.2f}%")
# 
#     else:
#         st.info("No predictions found yet. Go to 'Detect Spill' to make your first prediction!")
# 
#     # Option to clear history (for development/testing)
#     if st.sidebar.button("Clear Prediction History"):
#         conn = sqlite3.connect(DATABASE_NAME)
#         cursor = conn.cursor()
#         cursor.execute("DELETE FROM predictions")
#         conn.commit()
#         conn.close()
#         # Also remove saved image files
#         for f in os.listdir(PREDICTION_SAVE_DIR):
#             if f.startswith('original_') or f.startswith('mask_') or f.endswith('.db'):
#                 os.remove(os.path.join(PREDICTION_SAVE_DIR, f))
#         st.sidebar.success("Prediction history cleared!")
#         st.rerun() # Rerun to update the display

!pip install pyngrok -q

!pip install streamlit -q

!streamlit run app.py &>/dev/null&

from pyngrok import ngrok
import os
from google.colab import userdata

# Use the GOOGLE_API_KEY secret for ngrok authentication
# Make sure you have added NGROK_AUTH_TOKEN to the Colab secrets
# panel (under the 🔑 icon)
try:
    ngrok_auth_token = userdata.get('NGROK_AUTH_TOKEN')
    ngrok.set_auth_token(ngrok_auth_token)

    # Establish a tunnel to the Streamlit port 8501
    public_url = ngrok.connect('8501') # Modified to pass port as the first argument

    print(f"Streamlit app available at: {public_url}")
except Exception as e:
    print(f"An error occurred: {e}")
    print("Please make sure you have added your NGROK_AUTH_TOKEN to the Colab secrets panel (under the 🔑 icon).")

print(public_url)